In [60]:
import numpy as np

1-е задание

In [61]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [62]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [63]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

2-е задание

In [64]:
a_centered = a - mean_a

In [65]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [66]:
a_centered.shape

(5, 2)

Задание 3:

In [67]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [68]:
a_centered_sp

8.0

In [69]:
B = a_centered_sp/(a_centered.shape[0]-1)
B

2.0

Задание 4:

In [70]:
m = a.transpose()
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [71]:
C = np.cov(m)
C

array([[1. , 2. ],
       [2. , 4.3]])

Работа с pandas

In [72]:
import pandas as pd

Задание 1

In [73]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [74]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 
                    'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 
                    'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]}, 
                    columns = ['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2:

In [112]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [76]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [80]:
authors_stat_min = authors_price.groupby('author_name')['price'].min()
authors_stat_max = authors_price.groupby('author_name')['price'].max()
authors_stat_mean = authors_price.groupby('author_name')['price'].mean()

In [91]:
authors_stat_min = pd.DataFrame(authors_stat_min)
authors_stat_max = pd.DataFrame(authors_stat_max)
authors_stat_mean = pd.DataFrame(authors_stat_mean)
authors_stat_min

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [95]:
authors_stat_1=pd.merge(authors_stat_min, authors_stat_max, on='author_name', how='outer')

In [99]:
authors_stat=pd.merge(authors_stat_1, authors_stat_mean, on='author_name', how='outer')
authors_stat.columns = ['min_price', 'max_price', 'mean_price']
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

Задание 5:

In [114]:
t = pd.DataFrame({'cover': ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns = ['cover'])

In [115]:
authors_price=pd.concat([authors_price, t], axis=1)

In [116]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [117]:
table = pd.pivot_table(authors_price, values = 'price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)

In [126]:
book_info=table

In [123]:
book_info.to_pickle('book_info.pkl')

In [124]:
book_info2=pd.read_pickle('book_info.pkl')

In [131]:
book_info2==book_info

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True

In [128]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [132]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950